import os
import json
import logging
import time

logger = logging.getLogger(__name__)

# Base paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "data")
COLLAB_FILE = os.path.join(DATA_DIR, "collaborative.json")

def load_collab() -> dict:
    """
    Loads collaborative topics from data/collaborative.json.
    
    Returns:
        dict: The collaborative database.
    """
    os.makedirs(DATA_DIR, exist_ok=True)
    if not os.path.exists(COLLAB_FILE):
        return {}
    try:
        with open(COLLAB_FILE, "r", encoding="utf-8") as f:
            content = f.read().strip()
            if content:
                return json.loads(content)
    except Exception as e:
        logger.error(f"Failed to load collaborative file: {e}")
    return {}

def save_collab(data: dict):
    """
    Saves collaborative topics to data/collaborative.json.
    
    Args:
        data (dict): The collaborative database.
    """
    os.makedirs(DATA_DIR, exist_ok=True)
    try:
        with open(COLLAB_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, ensure_ascii=False)
    except Exception as e:
        logger.error(f"Failed to save collaborative file: {e}")

def join_topic(topic_id: str, username: str, query: str):
    """
    Registers that a username has joined a collaborative topic with a query.
    
    Args:
        topic_id (str): The unique identifier of the topic.
        username (str): The name of the joining user.
        query (str): The search query being run.
    """
    if not topic_id or not username:
        return
    db = load_collab()
    if topic_id not in db:
        db[topic_id] = {
            "topic_name": topic_id.replace("_", " ").title(),
            "users": {},
            "feed": []
        }
        
    db[topic_id]["users"][username] = {
        "last_active": time.time(),
        "last_query": query
    }
    
    db[topic_id]["feed"].append({
        "type": "join",
        "username": username,
        "query": query,
        "timestamp": time.time(),
        "message": f"User {username} joined the topic researching: '{query}'"
    })
    
    save_collab(db)

def post_finding(topic_id: str, username: str, query: str, report_snippet: str, sources: list):
    """
    Logs a research report generated by a user on the shared topic.
    
    Args:
        topic_id (str): Shared topic ID.
        username (str): Username who compiled the report.
        query (str): The query evaluated.
        report_snippet (str): Text snippet of the generated report.
        sources (list): List of sources used.
    """
    if not topic_id or not username:
        return
    db = load_collab()
    if topic_id not in db:
        db[topic_id] = {
            "topic_name": topic_id.replace("_", " ").title(),
            "users": {},
            "feed": []
        }
        
    db[topic_id]["feed"].append({
        "type": "research_run",
        "username": username,
        "query": query,
        "report_snippet": report_snippet[:500] + "..." if len(report_snippet) > 500 else report_snippet,
        "sources": sources,
        "timestamp": time.time(),
        "message": f"User {username} published a research report on: '{query}'"
    })
    
    save_collab(db)

def get_topic_feed(topic_id: str) -> dict:
    """
    Retrieves the full collaboration log and active users on the topic.
    
    Args:
        topic_id (str): Shared topic ID.
        
    Returns:
        dict: List of active users and feed events.
    """
    if not topic_id:
        return {"users": {}, "feed": []}
    db = load_collab()
    return db.get(topic_id, {"users": {}, "feed": []})

def get_all_topics() -> list:
    """
    Returns a list of all active shared topics.
    
    Returns:
        list: Active topics with details.
    """
    db = load_collab()
    return [
        {"id": tid, "name": tinfo.get("topic_name", tid), "user_count": len(tinfo.get("users", {}))}
        for tid, tinfo in db.items()
    ]
